### ISSUE TITLE
issue with BacklightCompensation

### ISSUE THREAD

**Issue by drkWiss** [SuslikV/cfg-cam#1]
Hey,
First of all thanks for this amazing tool, It saves me a lot of time.
My issue is that the LowLight Compensation check box won't save, but I found a workaround for it.

(It's not an issue anymore :) )

Regards,

**Comment by SuslikV** [comment]
Thank you for the feedback!

I noticed your issue too late, hope, all thing was arranged for you.

The handling of the mentioned option, https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/ksproperty-cameracontrol-auto-exposure-priority by cfg-cam not implemented yet. Because it is different method of how to manage device options - AVStream as I understand (more work to do).

The program v1.0 only uses:
[CameraControlProperty enumeration](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318253(v=vs.85).aspx)
[VideoProcAmpProperty enumeration](https://msdn.microsoft.com/en-us/library/windows/desktop/dd407328(v=vs.85).aspx)
That's all that was on my list.

**Comment by simplo** [comment]
Hi @drkWiss ! Could you pleas help me explaining which is the workaround to fix the "Low Compensation" issue?
I have same problem :(
Thank you!
