### ISSUE TITLE
Add an argument

### ISSUE THREAD

**Issue by Nocrak** [SuslikV/cfg-cam#2]
Hi, is there a way that you can add another argument to the .exe?
An argument that load the configurations.

I'm trying to call your .exe by C# but for some reason when I run it without arguments it does not run correctly.

**Comment by SuslikV** [comment]
Without first running with the `--savedev` key there is no `cam_sett.cfg` is created, so no where to load settings from. If nothing is changed in the graph (camera is plugged-in but not shown anywhere, no light-on) then the _.cfg_ file will be dummy list of the connected devices.

Because one file ( `cam_sett.cfg` ) is not a handy for usage, I'm using application this way:

- Saves just changed camera settings (camera is running).
`"C:\My programs\WebCameraConfig\WebCameraConfig.exe" --savedev --profile night`

it makes new `night.cfg` in the folder same as mentioned _.exe_ file (overwrites old without confirmation).

--------

- Applies settings to already running device.
`"C:\My programs\WebCameraConfig\WebCameraConfig.exe" --profile night`

applies settings saved in `night.cfg` file. 

No file extension required when loading or saving profiles, just name.
